### ISSUE TITLE
Opening another shell breaks the UI

### ISSUE THREAD

**Issue by hahohihu** [lthoerner/rush#33]
Opening another shell breaks the UI. 

This is what fish looks like: ![](https://i.imgur.com/iyam1De.png)

And bash just freezes and requires a complete restart.

Not too urgent, but adding it for documentation.

EDIT: Oh, actually, pretty significant, since it also breaks any TUI, e.g. htop.

**Comment by Eyesonjune18** [comment]
This will happen upon calling any interactive process. It is tied into the lack of support for user input to processes, as well as the lack of support for ANSI escape sequences.

**Comment by lthoerner** [comment]
Fixed as of 176cf8ed1335a1d77faed8f55ef3877020120dce
